#include <stdio.h>
#include <stdlib.h>
#include "gba.h"
#include "game.h"
                    /* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"


                    /* TODO: */
// Add any additional states you need for your app.
typedef enum {
    START,
    PLAY,
    WIN,
    LOSE,
} GBAState;

unsigned char isCheat;

int main(void) {
                    /* TODO: */
    // Manipulate REG_DISPCNT here to set Mode 3. //
    REG_DISPCNT = MODE3 | BG2_ENABLE;

    // Save current and previous state of button input.
    u32 previousButtons = BUTTONS;
    u32 currentButtons = BUTTONS;

    // Load initial game state
    GBAState state = START;

    // some initialization
    char *level1 = "noghoooghoooooooghokq*23...23.......23.rq.89...23.ab.ab.89.rq..*...23.23.23....rq.a111153.2415411b.rq.8000073.80000009.rq...*..23R....*....re1111b.23.a111111b.rf00009.89.80076009.rq............23....rq.a11b.a111b.23.a11cq.8073.80009.89.800dq...23............Bre1b.23.ab.a111111b.rf09.89.23.80076009.rq.....S23....23....rq.a11115411b.23.ab.rq.8000000009.89.89.rq..................rmppppppppppppppppppl";
    char *level2 = "noghoooghoooooooghokq*23...23.......23.rq.89...23.ab.ab.89.rq......23.23.23....rq.a111153.2415411b.rq.8000073.80000009.rq......23.....*....re1111b.23.a111111b.rf00009.89.80076009.rq............23....rq.a11b.a111b.23.a11cq.8073.80009.89.800dq...23............Ore1b.23.ab.a111111b.rf09.89.23.80076009.rq.....S23....23....rq.a11115411b.23.ab.rq.8000000009.89.89.rq..................rmppppppppppppppppppl";
    char *level3 = "noghoooghoooooooghokq*23...23.......23.rq.89.*.23.ab.ab.89.rq......23.23.23....rq.a111153.2415411b.rq.8000073.80000009.rq......23P....*....re1111b.23.a111111b.rf00009.89.80076009.rq............23....rq.a11b.a111b.23.a11cq.8073.80009.89.800dq...23......*.....Ore1b.23.ab.a111111b.rf09.89.23.80076009.rq.....S23....23....rq.a11115411b.23.ab.rq.8000000009.89.89.rq..................rmppppppppppppppppppl";
    char *levels[] = {level1, level2, level3};
    int currLevel = 0;
    isCheat = 0;

    GameMap *gameMap = new_GameMap(levels[currLevel]);
    Canvas *canvas = new_Canvas();
    int toRestart = 0;

    canvas->printStartPage(canvas);

    while (1) {
        currentButtons = BUTTONS; // Load the current state of the buttons


                    /* TODO: */
        // Manipulate the state machine below as needed //
        // NOTE: Call waitForVBlank() before you draw
        // int vx = 1;
        switch(state) {
            case START:
                // state = ?
                if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
                    canvas->printGameMap(canvas, gameMap, currLevel);
                    canvas->animateCharacters(canvas, gameMap);
                    state = PLAY;
                    toRestart = 0;
                }
                break;
            case PLAY:
                if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
                    canvas->printStartPage(canvas);
                    state = START;
                    toRestart = 1;
                } else {
                    if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
                        if (isCheat == 0) {
                            isCheat = 1;
                        } else {
                            isCheat = 0;
                        }
                        canvas->drawToggleMode(canvas);
                    }
                    Pacman *pacman = gameMap->pacman;
                    if (KEY_DOWN(BUTTON_UP, currentButtons)) {
                        pacman->moveDirection(pacman, DIRECTION_UP, gameMap);
                    } else if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
                        pacman->moveDirection(pacman, DIRECTION_RIGHT, gameMap);
                    } else if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
                        pacman->moveDirection(pacman, DIRECTION_DOWN, gameMap);
                    } else if (KEY_DOWN(BUTTON_LEFT, currentButtons)){
                        pacman->moveDirection(pacman, DIRECTION_LEFT, gameMap);
                    } else {
                        pacman->prevX = pacman->x;
                        pacman->prevY = pacman->y;
                    }
                    for (int i = 0; i < gameMap->numGhosts; i++) {
                        Ghost *ghost = gameMap->ghosts[i];
                        ghost->makeNextMove(ghost, gameMap);
                    }
                    canvas->animateCharacters(canvas, gameMap);
                }
                if (gameMap->getOutcome(gameMap) == GAME_OVER) {
                    canvas->printGameOverPage(canvas);
                    state = LOSE;
                    toRestart = 1;
                } else if (gameMap->getOutcome(gameMap) == GAME_WIN) {
                    delay(WIN_LOSE_DELAY);
                    currLevel = (currLevel + 1) % (sizeof(levels) / sizeof(char *));
                    canvas->printGameWinPage(canvas);
                    state = WIN;
                    toRestart = 1;
                }

                if (toRestart != 0) {
                    delete_GameMap(gameMap); // to avoid memroy leak!
                    gameMap = new_GameMap(levels[currLevel]);
                }

                // state = ?
                break;
            case WIN:
                if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
                    canvas->printStartPage(canvas);
                    state = START;
                }
                if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
                    canvas->printGameMap(canvas, gameMap, currLevel);
                    canvas->animateCharacters(canvas, gameMap);
                    state = PLAY;
                    toRestart = 0;
                }
                // state = ?
                break;
            case LOSE:
                if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
                    canvas->printStartPage(canvas);
                    state = START;
                }
                if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
                    canvas->printGameMap(canvas, gameMap, currLevel);
                    canvas->animateCharacters(canvas, gameMap);
                    state = PLAY;
                    toRestart = 0;
                }
                // state = ?
                break;
        }

        previousButtons = currentButtons; // Store the current state of the buttons
    }

    // UNUSED(previousButtons); // You can remove this once previousButtons is used

    // I don't think the code will ever reach here
    // but if possible let's do these nice things
    delete_Canvas(canvas);
    delete_GameMap(gameMap);

    return 0;
}
